### ISSUE TITLE
"case class" Stackoverflow

### ISSUE THREAD

**Issue by Mr-HHP** [mycaule/scalabug10604-testcase#1]
Hello, I have the same problem as you. I created a very large "case class" and encountered these errors while compiling. I solved the problem by increasing stack memory (-Xss2048m), but I don't understand the cause, do you know the cause?

**Comment by mycaule** [comment]
Hello,

As I remember, the default values are were too low, increasing the memory a bit should not be a problem.

The best answer at that time was this one : 
https://github.com/scala/bug/issues/10604#issuecomment-376543621

Also having too much fields in your `case class` definitely means your data model is not good and that you should break it down (normalize) if possible.
